Azure/k8s-deploy

- lib/input-parameters.js
- src/input-parameters.ts
Added non-empty validation to pullImageSecrets. This should fix issue #10.
> issue #10 fix missing name key

- lib/input-parameters.js
- src/input-parameters.ts
As I already created a PR for this on the release branch, here comes the fix for master.
> Fix #10 on master

- lib/utilities/manifest-utilities.js
- lib/utilities/resource-object-utility.js
- lib/utilities/strategy-helpers/deployment-helper.js
- src/utilities/manifest-utilities.ts
- src/utilities/resource-object-utility.ts
- src/utilities/strategy-helpers/deployment-helper.ts
Fixes https://github.com/Azure/k8s-deploy/issues/2 and some more bugs related to the replacement logic
> Fixing replaceLogic

- lib/input-parameters.js
- src/input-parameters.ts
Porting changes from master to fix #20
> Filter imagePullSecrets to contain only non-empty values (#14)

- action.yml
- Modification to the description of the action 💬
To optimise the marketplace search for this action ✌️
> Modified the description to optimise marketplace search

- action.yml
* modified description to optimise search
* modified wording
* added the AKS keyword
> Modified the description to optimise marketplace search (#31)

- .github/workflows/test.yml
- .gitignore
- __tests__/manifests/deployment.yml
- __tests__/run.test.ts
- jest.config.js
- lib/actions/promote.js
- lib/actions/reject.js
- lib/constants.js
- lib/input-parameters.js
- lib/kubectl-object-model.js
- lib/run.js
- lib/utilities/files-helper.js
- lib/utilities/kubectl-util.js
- lib/utilities/manifest-stability-utility.js
- lib/utilities/manifest-utilities.js
- lib/utilities/resource-object-utility.js
- lib/utilities/strategy-helpers/canary-deployment-helper.js
- lib/utilities/strategy-helpers/deployment-helper.js
- lib/utilities/strategy-helpers/pod-canary-deployment-helper.js
- lib/utilities/strategy-helpers/smi-canary-deployment-helper.js
- lib/utilities/string-comparison.js
- lib/utilities/tool-runner.js
- lib/utilities/utility.js
- package.json
- src/run.ts
- src/utilities/kubectl-util.ts
- tsconfig.json
> Test Cases for deploy

- __tests__/run.test.ts
- action.yml
- lib/actions/promote.js
- lib/actions/reject.js
- lib/constants.js
- lib/input-parameters.js
- lib/kubectl-object-model.js
- lib/run.js
- lib/utilities/files-helper.js
- lib/utilities/kubectl-util.js
- lib/utilities/manifest-stability-utility.js
- lib/utilities/manifest-utilities.js
- lib/utilities/resource-object-utility.js
- lib/utilities/strategy-helpers/canary-deployment-helper.js
- lib/utilities/strategy-helpers/deployment-helper.js
- lib/utilities/strategy-helpers/pod-canary-deployment-helper.js
- lib/utilities/strategy-helpers/smi-canary-deployment-helper.js
- lib/utilities/string-comparison.js
- lib/utilities/tool-runner.js
- lib/utilities/utility.js
- package.json
- src/input-parameters.ts
- src/kubectl-object-model.ts
- src/utilities/strategy-helpers/deployment-helper.ts
- src/utilities/strategy-helpers/pod-canary-deployment-helper.ts
- src/utilities/strategy-helpers/smi-canary-deployment-helper.ts
Optional Force flag added. If true, this will immediately remove resources from API and bypass graceful deletion.
> Optional force flag added

- __tests__/run.test.ts
- action.yml
- lib/constants.js
- lib/githubClient.js
- lib/input-parameters.js
- lib/kubectl-object-model.js
- lib/utilities/httpClient.js
- lib/utilities/strategy-helpers/deployment-helper.js
- lib/utilities/utility.js
- src/constants.ts
- src/githubClient.ts
- src/input-parameters.ts
- src/kubectl-object-model.ts
- src/utilities/httpClient.ts
- src/utilities/strategy-helpers/deployment-helper.ts
- src/utilities/utility.ts
Annotation and Label changes to handle multiple unique workflows and parallel runs of those during new commits across branches. [ADR](https://github.com/github/Microsoft-Attach/pull/11/files)
> Annotation and Label changes to handle multiple workflows across branches

- .github/ISSUE_TEMPLATE/blue-green-bug-bash.md
Adding template for blue-green strategy bug bash
> Update issue templates

- __tests__/run.test.ts
- action.yml
- lib/constants.js
- lib/githubClient.js
- lib/input-parameters.js
- lib/kubectl-object-model.js
- lib/utilities/httpClient.js
- lib/utilities/strategy-helpers/deployment-helper.js
- lib/utilities/utility.js
- src/constants.ts
- src/githubClient.ts
- src/input-parameters.ts
- src/kubectl-object-model.ts
- src/utilities/httpClient.ts
- src/utilities/strategy-helpers/deployment-helper.ts
- src/utilities/utility.ts
(Master)Annotation and Label changes to handle multiple workflows across branches
> (M)Annotation and Label changes to handle multiple workflows across branches

- README.md
- lib/utilities/strategy-helpers/ingress-blue-green-helper.js
- lib/utilities/strategy-helpers/smi-blue-green-helper.js
- src/utilities/strategy-helpers/ingress-blue-green-helper.ts
- src/utilities/strategy-helpers/smi-blue-green-helper.ts
> Fixing issues found in bug bash. (#71)

- README.md
- lib/utilities/strategy-helpers/ingress-blue-green-helper.js
- lib/utilities/strategy-helpers/smi-blue-green-helper.js
- src/utilities/strategy-helpers/ingress-blue-green-helper.ts
- src/utilities/strategy-helpers/smi-blue-green-helper.ts
Porting #71 to `releases/v1.4`
> [Port to releases/v1.4] Fixing issues found in bug bash.

- README.md
Added workflow samples for using the new env variables to enable traceability features for dockerfile, manifests, helmcharts and acr.
> Updated new features in Readme with sample workflows

- lib/utilities/utility.js
- src/utilities/utility.ts
Dockerfile path should be converted to link within current repo when relative path is given by user.
> Bug fix for dockerfile path for default

- lib/utilities/utility.js
- src/utilities/utility.ts
Dockerfile path should be converted to link within current repo when relative path is given by user.
> Bug fix for dockerfile path

- lib/utilities/utility.js
- src/utilities/utility.ts
Dockerfile path should be converted to link within current repo when relative path is given by user.
> Bug fix for dockerfile path v1.3

- __tests__/run.test.ts
- lib/utilities/strategy-helpers/deployment-helper.js
- lib/utilities/utility.js
- src/utilities/strategy-helpers/deployment-helper.ts
- src/utilities/utility.ts
> Fixing label values of workflow names with spaces

- package-lock.json
- package.json
To fix vulnerability alert for `underscore`
> Bump @actions/tool-cache from 1.1.1 to 1.1.2

- action.yml
- lib/input-parameters.js
- src/input-parameters.ts
Removing optional input "Arguments" from the actions as part of #113
> Removing optional input arguments from the action

- lib/run.js
- src/run.ts
> Sending a warning instead of throwing error when KUBECONFIG is missing.

- src/utilities/strategy-helpers/smi-canary-deployment-helper.ts
> fix smi weight bug

- .gitignore
- lib/actions/promote.js
- lib/actions/reject.js
- lib/constants.js
- lib/docker-object-model.js
- lib/githubClient.js
- lib/input-parameters.js
- lib/kubectl-object-model.js
- lib/run.js
- lib/utilities/files-helper.js
- lib/utilities/httpClient.js
- lib/utilities/kubectl-util.js
- lib/utilities/manifest-stability-utility.js
- lib/utilities/manifest-utilities.js
- lib/utilities/resource-object-utility.js
- lib/utilities/strategy-helpers/blue-green-helper.js
- lib/utilities/strategy-helpers/canary-deployment-helper.js
- lib/utilities/strategy-helpers/deployment-helper.js
- lib/utilities/strategy-helpers/ingress-blue-green-helper.js
- lib/utilities/strategy-helpers/pod-canary-deployment-helper.js
- lib/utilities/strategy-helpers/service-blue-green-helper.js
- lib/utilities/strategy-helpers/smi-blue-green-helper.js
- lib/utilities/strategy-helpers/smi-canary-deployment-helper.js
- lib/utilities/string-comparison.js
- lib/utilities/tool-runner.js
- lib/utilities/utility.js
- package-lock.json
- src/utilities/strategy-helpers/smi-canary-deployment-helper.ts
Building JavaScript and publishing to main branch
> Build JavaScript

- src/utilities/workflowAnnotationUtils.test.ts
- src/utilities/workflowAnnotationUtils.ts
ref #189 
Add prefix for annotations to avoid key collisions/overwrites
> prefix for annotations

- action.yml
> upgraded to Node16

- README.md
- action.yml
- src/strategyHelpers/deploymentHelper.ts
- src/types/deploymentStrategy.test.ts
- src/types/deploymentStrategy.ts
> switch none deployment strategy to basic

- src/strategyHelpers/deploymentHelper.ts
- src/utilities/workflowAnnotationUtils.test.ts
- src/utilities/workflowAnnotationUtils.ts
> clean labels

- README.md
- jest.config.js
- src/run.ts
- src/types/errorable.ts
- src/utilities/fileUtils.test.ts
- src/utilities/fileUtils.ts
This PR adds functionality to fetch and deploy manifests from URLs
> Deploy with Manifests from URLs

- .github/workflows/run-integration-tests-basic.yml
- .github/workflows/run-integration-tests-private.yml
- action.yml
- src/types/kubectl.test.ts
- src/types/kubectl.ts
- src/types/privatekubectl.test.ts
- src/types/privatekubectl.ts
- test/integration/k8s-deploy-test.py
Fixes #256 
Identical to [PR 257](https://github.com/Azure/k8s-deploy/pull/257) but that contained an unsigned commit, so had to push everything into just one commit before merging.
> Fixed Private Cluster Namespace Bug

- src/strategyHelpers/deploymentHelper.ts
> Fixed Resources Being Annotated Multiple Times

- .github/workflows/release-pr.yml
- CHANGELOG.md
add new release workflow to upgrade our release process to better fit github actions best practices
> release workflow

- package-lock.json
- package.json
- src/types/kubectl.test.ts
upgrade to typescript 5 to get rid of some cves.
remove an empty test block
> upgrade to typescript 5

- CHANGELOG.md
- README.md
- src/actions/deploy.ts
- src/actions/promote.ts
- src/strategyHelpers/deploymentHelper.ts
- src/utilities/manifestStabilityUtils.test.ts
- src/utilities/manifestStabilityUtils.ts
New release v5.0.1
Add fleet types as const
> v5.0.1 Release with Fleet Types

- CHANGELOG.md
add release v5.0.2 to changelog
> Release v5.0.2

- CHANGELOG.md
cutting a release with the type insensitivity changes
> release v5.0.3

- .github/CODEOWNERS
aks-atlanta team is deprecated, update to new owners team
> update owner team
