- __tests__/blue-green-helper.test.ts
- __tests__/manifests/bg-smi.yml
- __tests__/manifests/bg.yml
- action.yml
- lib/actions/promote.js
- lib/actions/reject.js
- lib/input-parameters.js
- lib/run.js
- lib/utilities/manifest-utilities.js
- lib/utilities/resource-object-utility.js
- lib/utilities/strategy-helpers/blue-green-helper.js
- lib/utilities/strategy-helpers/deployment-helper.js
- lib/utilities/strategy-helpers/ingress-blue-green-helper.js
- lib/utilities/strategy-helpers/service-blue-green-helper.js
- lib/utilities/strategy-helpers/smi-blue-green-helper.js
- src/actions/promote.ts
- src/actions/reject.ts
- src/input-parameters.ts
- src/run.ts
- src/utilities/manifest-utilities.ts
- src/utilities/resource-object-utility.ts
- src/utilities/strategy-helpers/blue-green-helper.ts
- src/utilities/strategy-helpers/deployment-helper.ts
- src/utilities/strategy-helpers/ingress-blue-green-helper.ts
- src/utilities/strategy-helpers/service-blue-green-helper.ts
- src/utilities/strategy-helpers/smi-blue-green-helper.ts
Like the existing canary deployment strategy, added blue-green deployment strategy to the actions with three route-methods - service, ingress and smi. also added version-switch-buffer input takes input in minutes. It waits for the given time before routing service/ingress/trafficsplit to new deployments in deploy step. 
Reference image for how service routing should work.
> added blue green strategy

- __tests__/run.test.ts
- lib/input-parameters.js
- lib/utilities/manifest-utilities.js
- lib/utilities/resource-object-utility.js
- src/input-parameters.ts
- src/utilities/manifest-utilities.ts
- src/utilities/resource-object-utility.ts
- Fixes #86 
- Added yaml parser an combined the functions for image pull secrets and image substitution
- Fixed input parameter logic to handle empty value for images (currently it was taking it as [' '] instead of [])
- Fixed L0s which were not working because of the new changes
> Add yaml parser to image substitution logic

- __tests__/run.test.ts
- lib/utilities/kubectl-util.js
- src/utilities/kubectl-util.ts
This PR adds the arch detection to kubectl download using [`os.arch()`](https://nodejs.org/api/os.html) call. It won't work on all arch's, but should support amd64, arm and arm64 on Linux (and some more - https://kubernetes.io/docs/setup/release/notes/#client-binaries). If the action is run on non-supported arch by kubectl it won't be able to download and will fail.
Should fix #115.
> Added arch detection to kubectl download

- __tests__/run.test.ts
- src/input-parameters.ts
- src/run.ts
This PR adds support for providing input manifests separated by both commas and newline as delimiter.
The following formats should be supported post this change
```
manifests: |
a.yml, b.yml, c.yml
```
```
manifests: |
a.yml
b.yml, c.yml
```
```
manifests: |
a.yml
b.yml
c.yml
```
```
manifests: |
a.yml;b.yml;c.yml
```
> Supporting both comma and new line as delimiters for manifests

- README.md
- action.yml
- src/utilities/dockerUtils.ts
The avoid warnings during deployment process, this PR makes the pulling of images to find out Dockerfile's path switchable off.
Cases where there was the warning in former releases: 
- Action executes on self-hosted runners without Docker installed or other containerization technology installed (e.g. Podman)
- Workflow doesn't have access to the registry of the images
> Making pulling of images switchable

- README.md
- action.yml
- src/strategyHelpers/deploymentHelper.ts
In order to fix https://github.com/Azure/k8s-deploy/issues/149, I tried my very best to add a feature to make it possible switching off annotations to the namespace. 
The former behaviour of the action is considered to be the default, so behaviour only changes in case somebody explicitly sets the new input  parameter to `false`
> Making namespace annotation switchable

- .github/workflows/unit-tests.yml
- package.json
- src/types/kubectl.test.ts
- src/types/kubectl.ts
ref #163
- omit namespace arg if namespace == 'default'
- added unit tests back onto main (they still only ran on master)
- bump jest version to fix peer dep conflict
> omit namespace arg for default namespace

- src/utilities/workflowAnnotationUtils.test.ts
- src/utilities/workflowAnnotationUtils.ts
I was running into this kind of error, while trying to deploy to my k8s cluster. 
```
error: invalid label value: "workflowFriendlyName=Develop_/_Deploy_To_k8s_Cluster": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
```
In addition to https://github.com/Azure/k8s-deploy/pull/211 which does not remove slashes, I replaced slashes with dashes. This fixes #105 again which is already merged and fixed, but the implementation misses consideration of slashes, as mentioned here https://github.com/Azure/k8s-deploy/issues/105#issuecomment-1127785348  
What I did in this PR: In …
> consider slashes while cleaning labels

- .github/ISSUE_TEMPLATE/bugReportForm.yml
- .github/ISSUE_TEMPLATE/featureRequestForm.yml
Hi 👋 . I just wanted to open a new issue (bug report), but the form seems not displayed due to syntax errors.
Only the repository link defined in `config.yml` are displayed. The other files (`bugReportForm.yml` and `featureRequestForm.yml`) are not displayed due to the format error.
- Fix syntax errors in issue-forms for displaying them as candidates.
- Apply `textarea` for description fields instead of `input` (for allowing longer and multi-line text).
> Fix issue form syntax errors

- src/utilities/workflowAnnotationUtils.test.ts
- src/utilities/workflowAnnotationUtils.ts
- abstract a couple methods in the label cleaning to avoid drift
- avoid having regexes in the tests themselves
> abstract methods to avoid drift

- src/types/privatekubectl.test.ts
- src/types/privatekubectl.ts
Move the error check for Azure earlier, so that a well defined error is thrown on error instead of a JSONSyntax error.
The issue is that when Azure returns an error, like when there's an issue with the access to the principal used. When this happens, the stdout field will be an empty string, and the error message will be set to a non-json string.
> Check for error from Azure when using the private-cluster feature

- .github/workflows/codeql.yml
codeql v1 is deprecated, so we need to upgrade to allow the check to pass and unblock PRs
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
updated to removed the checkout HEAD^2 as this is no longer recommended in the docs
https://github.com/Azure/k8s-deploy/actions/runs/3870184983/jobs/6596900421#step:4:9
> upgrade codeql

- src/actions/deploy.ts
- src/strategyHelpers/blueGreen/blueGreenHelper.ts
- src/strategyHelpers/blueGreen/ingressBlueGreenHelper.ts
- src/strategyHelpers/blueGreen/serviceBlueGreenHelper.ts
- src/strategyHelpers/blueGreen/smiBlueGreenHelper.ts
- src/strategyHelpers/canary/canaryHelper.ts
- src/strategyHelpers/deploymentHelper.ts
- src/types/k8sObject.ts
- src/types/kubectl.test.ts
- src/types/kubectl.ts
- src/types/privatekubectl.ts
- src/utilities/kubectlUtils.ts
- src/utilities/manifestStabilityUtils.ts
- src/utilities/manifestUpdateUtils.ts
Closes #163 
Lets users deploy resources in multiple namespaces elegantly
> Fixes multiple namespaces bug

- package-lock.json
- package.json
- src/strategyHelpers/blueGreen/blueGreenHelper.ts
With the current implementation of the “Service” route-method of the Blue-Green strategy, if the manifest file contains `Service` object _before_ `Deployment` ones, then, `Service` isn’t updated with the right labels selector.
<details><summary>Sample affected manifest file</summary>
```yaml
apiVersion: v1
kind: Service
metadata:
name: nginx-service
spec:
selector:
app: nginx
ports:
- protocol: TCP
port: 80
targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: nginx-deployment
labels:
app: nginx
spec:
replicas: 1
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
containers:
- name: nginx
image: nginx
ports:
- containerPort: 80
```
</details>
To fix this issue, update `getManifestObjects()` function in the …
> Fix “Service” route-method of the Blue-Green strategy with some manifest files

- .github/workflows/run-integration-tests-bluegreen-ingress.yml
- .github/workflows/run-integration-tests-bluegreen-service.yml
currently PRs can't merge because the minikube version isn't working with the new ubuntu tag
> bump minikube to fix runner deps

- .github/workflows/release-pr.yml
the current workflow uses a short hash which apparently isn't supported
> bump release workflow sha

- .github/workflows/release-pr.yml
bump the commit hash for our release workflow to include fixes to the release process including patching .gitignore to include missing lib directory on release branches
> add release worklflow artifact fix

- package.json
use a local bin link just for ncc to get a bin link prior to calling with npx, as it isn't working correctly on our action runners
using just `npx ncc` isn't working since the install/build step doesn't add bin links, and we have to manually add one for ncc which we use for building
link to a working version on my fork https://github.com/davidgamero/k8s-deploy/actions/runs/6751019098/job/18354429862
> add installing ncc to build

- src/utilities/dockerUtils.ts
In Typescript/Javascript an empty string split on newline is going to produce an array with an empty string.
=> "".split('\n')
[""]
This causes the action to produce a warning, unless `pull-images` is set to false.
Failed to get dockerfile path for image : Error: The process '/usr/bin/docker' failed with exit code 1
Filtering the list to remove any zero-length strings from the array solves this issue.
> fix: ensure imageNames are not empty strings

- action.yml
Fix warning like: Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20:
> node.js20 update

- .github/workflows/codeql.yml
- .github/workflows/release-pr.yml
- CHANGELOG.md
- README.md
- package.json
create the new v5 release with node20 updates and the required workflow version bumps
> create v5 node20 release

- src/actions/deploy.ts
- src/actions/promote.ts
- src/strategyHelpers/deploymentHelper.ts
- src/utilities/manifestStabilityUtils.test.ts
- src/utilities/manifestStabilityUtils.ts
Added functionality to deploy to fleet hub cluster
> enable fleet cluster deployment

- .github/workflows/run-integration-tests-basic.yml
- .github/workflows/run-integration-tests-bluegreen-ingress.yml
- .github/workflows/run-integration-tests-bluegreen-service.yml
- .github/workflows/run-integration-tests-bluegreen-smi.yml
- .github/workflows/run-integration-tests-canary-pod.yml
- .github/workflows/run-integration-tests-canary-smi.yml
- .github/workflows/run-integration-tests-private.yml
- .github/workflows/run-integration-tests-resource-annotation.yml
pin to ubuntu 22.04 until https://github.com/medyagh/setup-minikube/issues/565 is resolved, it's blocking our integration tests
upgrade minkube and k8s version in integrations
several tests are failing on PRs and this maintenance task is overdue
> pin ubuntu 22.04, upgrade minikube and k8s version in integrations

- .github/workflows/defaultLabels.yml
- .github/workflows/prettify-code.yml
- .github/workflows/run-integration-tests-basic.yml
- .github/workflows/run-integration-tests-bluegreen-ingress.yml
- .github/workflows/run-integration-tests-bluegreen-service.yml
- .github/workflows/run-integration-tests-bluegreen-smi.yml
- .github/workflows/run-integration-tests-canary-pod.yml
- .github/workflows/run-integration-tests-canary-smi.yml
- .github/workflows/run-integration-tests-private.yml
- .github/workflows/run-integration-tests-resource-annotation.yml
- .github/workflows/unit-tests.yml
This PR updates our GitHub Actions workflow by **pinning dependencies to specific commit SHAs**, ensuring enhanced security, reliability, and consistency across builds.  
* **Pinned for example `actions/setup-python@v5` to its SHA** (`0b93645`) to prevent unexpected updates.  
* **Ensured all GitHub Actions dependencies are using SHA references** instead of floating tags.  
* **Security** – Prevents supply chain attacks by ensuring that only the verified version of an action runs.  
* **Stability** – Guarantees that workflows are consistent across runs, avoiding unexpected behavior from upstream changes.  
* **Performance** – Helps maintain reproducible builds by locking dependencies to known-good versions.  
Thanks
> Pin Dependencies for Improved Security and Stability  

- action.yml
Currently, not adding the new resource-type input in action.yml is causing this warning: 
To avoid confusion, we will add it to remove the warning.
> Adding to action.yml

- src/actions/deploy.ts
- src/actions/promote.ts
- src/inputUtils.test.ts
- src/inputUtils.ts
- src/run.ts
- src/strategyHelpers/deploymentHelper.ts
- src/utilities/manifestStabilityUtils.ts
- allow case-insensitive matching of resource types
- centralize core.getInput retrieval to run.ts for `resourceType`
- add tests for case-insensitive resource type and throw on unknown resource type
> case-insensitive resource type

- README.md
- action.yml
- src/strategyHelpers/blueGreen/blueGreenHelper.ts
- src/strategyHelpers/canary/podCanaryHelper.ts
- src/strategyHelpers/canary/smiCanaryHelper.ts
- src/strategyHelpers/deploymentHelper.ts
- src/types/kubectl.test.ts
- src/types/kubectl.ts
- Add serverSide parameter to kubectl.apply() method
- Update all deployment strategy helpers to support server-side flag
- Add comprehensive unit tests for server-side functionality
- Follow existing force option implementation pattern
- Maintain backward compatibility with optional parameter
Addresses PR #312 and fixes issue #311 
Credits to @krikooo for the first #312
> add server-side option for kubectl apply commands

- README.md
- action.yml
- This PR adds timeout input description to README
> Added timeout input description to README
